### ISSUE TITLE
rename arch_messages => messages

### ISSUE THREAD

**Issue by adilhafeez** [katanemo/arch#171]
In the code we send message history to user api server. We initially thought [arch_messages](https://github.com/katanemo/arch/blob/main/crates/common/src/consts.rs#L18) would be a good name for the messages. But we think using `messages` as key would be better as it aligns with [ChatCompletion](https://platform.openai.com/docs/guides/text-generation/user-messages) requests format.

In this issue we want to rename arch_messages => messages and make sure all the wiring in the code is working as expected.

**Comment by salmanap** [comment]
This was merged in #211
