### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by xyproto** [katanemo/arch#187]
Ask any open source enthusuast what "Arch" is, and chances are good that they will reply "Arch Linux".

Please consider if "Arch" is a good name for this project.

**Comment by salmanap** [comment]
That's a fair comment - we do name the cli as "archgw" and I think we should consider this feedback early on in the project. Thank you for taking the time/effort to make this suggestion. We'll update this thread in 48 hours with suggestion/decision

**Comment by salmanap** [comment]
The team discussed this at length - for now, we will keep arch. Likely to change to archgw if we continue to get this feedback from the community
