### ISSUE TITLE
[llm-gateway] add tft and tot metrics and add them to grafana dashboard

### ISSUE THREAD

**Issue by adilhafeez** [katanemo/arch#246]
Add TFT and total request time in llm-gateway.

For TFT the timer should be started when the [request is received](https://github.com/katanemo/arch/blob/main/crates/llm_gateway/src/stream_context.rs#L141-L161) and timer should end then [first token is received](https://github.com/katanemo/arch/blob/main/crates/llm_gateway/src/stream_context.rs#L318) from upstream LLM.

The unit for metric should be milliseconds and should be stored in [WasmMetrics struct](https://github.com/katanemo/arch/blob/main/crates/llm_gateway/src/filter_context.rs#L16-L19).

**Comment by salmanap** [comment]
We need the following metrics instrumented

1. Time to first token (TTFT): This is how quickly users start seeing the model’s output after entering their query. Low waiting times for a response are essential in real-time interactions, but less important in offline workloads. This metric is driven by the time required to process the prompt and then generate the first output token.
2. Time per output token (TPOT): Time to generate an output token for each user that is querying the system. 
3. Latency = TTFT + (TPOT) * (the number of tokens to be generated)
4. Output sequence length (OSL) - Total tokens generated
4. Input sequence length (ISL) - Total input tokens 

We need the following metrics histograms in 5 mins, 15 mins, 30 mins, 1 hour, 24 hours, 7 day granularity. 

1. Average (p50)
2. P90 (90th percentile)
3. p95 (95th percentile)
4. p99 (99th percentile)
